name = "cutetopop-worker"
main = "src/index.js"
compatibility_date = "2025-09-06"

# Static assets directory
[assets]
directory = "./public"

# Observability configuration - from your recent commit
[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

# D1 Database binding
# Allows worker to access database via env.DB
[[d1_databases]]
binding = "DB"
database_name = "cutetopop-db"
database_id = "f9d232d7-69ed-4e19-8238-9970badd54d6"


# KV Namespace for caching images list
[[kv_namespaces]]
binding = "IMAGES_CACHE"
id = "b3a4366fb67e42ccbdeaa92d0f2cb376"
preview_id = "112191adc1ea4acb85f38d80370200f8"

# R2 Bucket for image storage
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "cutetopop-images"
preview_bucket_name = "cutetopop-images-preview"
