{
    "name": "cutetopop-worker",
    "main": "src/index.js",
    "compatibility_date": "2025-09-06",
    "assets": {
        "directory": "./public"
    }
}
# wrangler.toml (wrangler v3.88.0^)
[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true